spring:
  application:
    name: taotao-order-service
  datasource:
      url: jdbc:mysql://172.16.101.153:3306/taotao
      username: root
      password: abc123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  typeAliasesPackage: com.meng.taotaoorderservice.entity
  mapperLocations: classpath:mapper/*.xml